language: csharp
solution: net-sdk.sln

script:
  - xbuild /p:Configuration=Release net-sdk.sln /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False

deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd net-sdk && nuget pack net-sdk.nuspec -Version 1.0.4 -IncludeReferencedProjects -Prop Configuration=Release && nuget push *.nupkg 'dbb9424a-7913-4c63-b59d-2c3525eb2fb6' -verbosity detailed
  on:
    branch: master
  